// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD__260_Sygz25Bwg079FdVwnqWVpt5ksg',
    appId: '1:1031366668484:web:e180b24908c3d501391991',
    messagingSenderId: '1031366668484',
    projectId: 'tourm-61806',
    authDomain: 'tourm-61806.firebaseapp.com',
    storageBucket: 'tourm-61806.appspot.com',
    measurementId: 'G-W2JJ7QPZ7M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCtQNE6Ma2Gv2DNEbT6KNtf57oVTQztADk',
    appId: '1:1031366668484:android:2b64698d9d94cb96391991',
    messagingSenderId: '1031366668484',
    projectId: 'tourm-61806',
    storageBucket: 'tourm-61806.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDk2THMZ-8O38oHC11H9aB6F0vKtbmRqGo',
    appId: '1:1031366668484:ios:9f83956cd1304ee0391991',
    messagingSenderId: '1031366668484',
    projectId: 'tourm-61806',
    storageBucket: 'tourm-61806.appspot.com',
    iosBundleId: 'com.example.tm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDk2THMZ-8O38oHC11H9aB6F0vKtbmRqGo',
    appId: '1:1031366668484:ios:bb95377155e0fe8e391991',
    messagingSenderId: '1031366668484',
    projectId: 'tourm-61806',
    storageBucket: 'tourm-61806.appspot.com',
    iosBundleId: 'com.example.tm.RunnerTests',
  );
}
